### ISSUE TITLE
[SUGGESTION] direct load/export of individual g brick part

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#21]
I'd be great if we could - besides the "standard" loading of the whole brick selected from the table/list of LDD bricks you already have as a option - to be able to load individual .g brick part. After clicking this option open file dialog would open in the LOD0 folder where we could select one or even multiple different g parts of different bricks, not just the g parts of the same brick - this should also apply to the reversed option, that is direct output to 3D file.

Reason? I have many instances where I need/want to slightly modify just specific g part, not whole brick. Sure, I can simply load whole brick, export to 3D, and once in the 3D editor simply delete those parts I do not need. But it unnecessary adding additional work to be done when we could do it simple way described above right away.

**Comment by Polymaker** [comment]
It is possible to open a brick from a G or XML file with the menu:
![image](https://github.com/Polymaker/ldd-brick-editor/assets/6391719/85643946-4f9d-41d3-a487-192463760742)

But selecting either a G file (g, g1, g2, etc) or the XML file will load all the G files and the XML file because the app is designed to edit the whole brick.

The short answer is that the G files and the XML are intertwined, and editing a G file without loading the XML file could cause issues and produce invalid G files because some data points to indexes in the XML file.
