### ISSUE TITLE
[SUGGESTION] exported LDD brick to 3D material color

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#23]
When I export the brick mesh as 3D to be edited in a 3D editor (Blender in my case), it is in black.

Could you make option to set 3D file mesh output color? For instance, in LDD it is red by default (when in LDD EXTENDED MODE which I take/consider a profi user mode - most of us working with custom bricks probably already are using this mode exlusively, I guess).

Or could you at least set it to LDD's default red color instead of the black?

**Comment by Polymaker** [comment]
The exported meshes have default (empty) materials so the color you get seems to be applied by your editor as a sort of default color. For me the bricks are always gray when importing into blender, the same as the default cube loaded by blender.

I don't really see the point of having this feature because it is enterally esthetical and people that want to render the brick will mostly use a custom shiny/plastic material. 

If it is not complicated I may add the feature but it is not in my priorities.
