### ISSUE TITLE
[SUGGESTION] Brick part names in Project Tree

### ISSUE THREAD

**Issue by fafayqa** [Polymaker/ldd-brick-editor#29]
When I import mesh via "File > Import from LDD" part name sin Project Tree have some anonymous names like Part0, Part1 etc. - why this? It would be much more logical to incorporate in some way also the brick ID into it.

I prolly understand your naming logic where you are taking it from the brick sections (g parts) where g becomes part0, g1 becomes Part01 etc., but this way we are missing the original brick name (ID) which is quite a pity I would say.

So you could implement it somehow, either replace the actual Part0 with brick ID + part extension - most preferable option to me (like 3003_g, 3003_g1, 3003_g2 etc.) or if you still want to maintain the actual naming logic then prolly like 3003_Part0, 3003_Part1, 3003_Part2 etc.

**Comment by Polymaker** [comment]
The different "sections" of a brick are actually the surfaces in the project tree.
The "Main surface" is the "brickxxx.g", the "Decoration surface 1" is "brickxxx.g1" and so on.

The "Part0" element you are talking about is actually a sub-element (I call them components) of the brick model.
LDD has a functionality called culling, in which when a stud is hidden by a connected brick, the 3D data of this stud is unloaded from memory to improve performance. To be able to do this, the G file format has a section describing how the model is divided. 
They are four types of sub-elements:

- The main brick model (which is called Part in the app)
- A stud
- Understud (the bottom of a brick, called female stud in the app)
- A brick tube (the tube inside some bricks)

Here is an example of a 2x2 brick:
![image](https://github.com/Polymaker/ldd-brick-editor/assets/6391719/8331221d-8fdc-4237-bcc2-d447b0ad2f7e)


Generally there is only one Part element but I've seen some LDD bricks with more due to how the 3D data was ordered.
Also culling seems to only be intended for main surfaces and not decoration surfaces as I have never seen a "*.gx" file with sub-elements. 

As to your request to include the brick number in the naming of elements in the project tree, I don't see the point.
You cannot edit more than one brick at once and the brick ID is shown in the title bar, the 3D view tab and in the Part properties panel.

**Comment by fafayqa** [comment]
Well, if you really do not see my point I can tell you one right away: much easier orientation in the whole "thing" by simple "look at the names under the Project Tree->Surfaces->Elements".

Like why do you think it is somewhat more logical and more convenient having parts named basically anonymously instead of the actual brick ID they came from, hm?

Like what is more telling to you: "Part0" (and if I am correct the way I understood it there could be theoretically zillions of different "Part0" if more than 1 brick is imported, right? - totally anonymous name that tells you nothing about the src brick, only letting you know it is the main part, exactly the same you would get if the brick would contain brick ID it came from  + the .g* ...as the ones that actually would use your app would in most cases be advanced users - I cannot see any average one using it, no way my friend - and in that case it is understood such person would know that .g is main brick and .g* subparts, without saying!) or for example "brick3001_g"? That way just by pure look you immediately know which part of which brick you are dealing or want to deal...easy as that.

Or why you even have to first select it and then look elsewhere just to get the name of the brick the specific part came from???

It does not seem too logical to me, but hey, once again: you app, your decisions, tho as I said I would most definitely change this, cos it is not good way of naming in my oppinion.
